### ISSUE TITLE
VLESS问题

### ISSUE THREAD

**Issue by Ivan-ggg** [lyz7805/v2ray4flyio#11]
请问，单纯修改v2ray.sh中的inbounds代码，无法启用VLESS协议，请问还有哪里需要修改吗？
`   "inbounds": [`
`        {`
`            "listen": "0.0.0.0",`
`            "port": 443,`
`            "protocol": "vless",`
`            "settings": {`
`                "clients": [`
`                    {`
`                        "id": "$UUID",`
`                    }`
`                ],`
`                "decryption": "none"`
`            },`
`            "streamSettings": {`
`                "network": "ws",`
`                "wsSettings": {`
`                "path": "/xxxxx"`
`                }`
`            }`
`        }`
`    ],`

**Comment by lyz7805** [comment]
你这样配置就属于 VLESS + WS 连接，可参照官方 VLESS + TCP 示例：
[VLESS + TCP](https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP/README.md)

But:
但是官方明确提醒：
# （目前）请勿使用此配置过墙，记得套 TLS

因为官方在对[VLESS](https://www.v2fly.org/config/protocols/vless.html)文档介绍中提到：
> **目前 VLESS 没有自带加密，请用于可靠信道，如 TLS。**

-------
So:
建议 VLESS + TLS + WS 方案，具体配置可参照官方示例：
[VLESS over TCP with TLS + 回落 & 分流 to WebSocket（进阶配置）
](https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS-WS%20(recommended)/README.md)

**Comment by Ivan-ggg** [comment]
是这样的，我用上面VLESS的inbounds代码整段替换掉VMess的inbounds代码，然后github actions自动部署成功后，节点无法使用，连不上。原来的vmess还能用。。。（我上传时修改了path，可以用不同的path验证部署的版本。）
是否每次重新部署，是不清除原来的程序的？需要清空一次再部署？

**Comment by Ivan-ggg** [comment]
找到问题了，下面的这行
"id": "$UUID",
最后多了个,
删除后部署成功，已解决，谢谢！

**Comment by lyz7805** [comment]
> 是这样的，我用上面VLESS的inbounds代码整段替换掉VMess的inbounds代码，然后github actions自动部署成功后，节点无法使用，连不上。原来的vmess还能用。。。（我上传时修改了path，可以用不同的path验证部署的版本。） 是否每次重新部署，是不清除原来的程序的？需要清空一次再部署？

每次部署运行都是拉取最新版的 V2RAY 运行的，只要代码中配置不变，最后运行结果是不影响的

你加了VLESS不过还是建议不要直接用，不加TLS你那就是在裸奔

**Comment by zhuzhengfei** [comment]
使用VLESS也会加TLS的，按照这个配置好后，使用的就是flyio的根目录通配符证书（*.fly.dev）

**Comment by Ivan-ggg** [comment]
使用VLESS也会加TLS的，按照这个配置好后，使用的就是flyio的根目录通配符证书（*.fly.dev）

**Comment by lyz7805** [comment]
那样VLESS应该会比Vmess好点，等我有时间了再研究研究，把VLESS加上。
