### ISSUE TITLE
初次运行报错

### ISSUE THREAD

**Issue by zyp997** [lyz7805/v2ray4flyio#12]
Create app failed.

Error: Process completed with exit code 1.

flyio是还要绑卡才行吗？

**Comment by lyz7805** [comment]
可以参照这一步 https://github.com/lyz7805/v2ray4flyio/issues/7#issuecomment-1016241611 修改下代码，看看创建时候具体错误是什么。

fly.io确实需要绑卡，#7 中那个朋友错误就是`Error We need your payment information to continue!`，我估计你的也是这种情况

**Comment by zyp997** [comment]
@lyz7805 我新注册了个账号，绑卡之后就能成功部署了。
建议在 readme 中提醒一下。注册的时候直接绑卡，要不然跳过绑卡的那一步，连去哪绑卡都找不到。。
顺便说一下，我是用的银联的能够成功绑卡。
