### ISSUE TITLE
执行到第三部的时候报错

### ISSUE THREAD

**Issue by yx10010** [lyz7805/v2ray4flyio#14]
Error No access token available. Please login with 'flyctl auth login'   通过网页版获取或者本地获取的密钥替换main.yml里面的FLY_API_TOKEN出现前面的错误，求大佬指点

**Comment by lyz7805** [comment]
**请注意看[配置部署](https://github.com/lyz7805/v2ray4flyio#%E9%85%8D%E7%BD%AE%E9%83%A8%E7%BD%B2)第二步，需要将三个变量设置成GitHub Actions的安全字段。**
![image](https://user-images.githubusercontent.com/19458454/154384554-80b94c2a-2707-480a-b28c-f9827a48324c.png)

> 这样操作是在你不需要改代码情况下直接就能部署，而且也防止Token、UUID和APP_NAME泄露，被不怀好意的人恶意使用。
---
### 具体操作可以看下图：
![image](https://user-images.githubusercontent.com/19458454/154384988-2313224b-1b3d-4137-a2e6-ff3a888550ca.png)

**Comment by yx10010** [comment]
感谢大佬，我尝试一下

**Comment by yx10010** [comment]
已经OK啦  感谢大佬,最近发现另外一个容器部署koyeb目前是不需要绑定卡的，大佬有时间能不能帮搞一下

**Comment by lyz7805** [comment]
嗯，我抽空了解下
