### ISSUE TITLE
能出个视频教程就完美了！

### ISSUE THREAD

**Issue by kitkw** [lyz7805/v2ray4flyio#15]
小白有难度

**Comment by lyz7805** [comment]
**视频教程我暂时没考虑**

`README` 中步骤已经写的很清楚了，如果有疑问，可以直接提出，我会给你解答。

**Comment by LeeTalor** [comment]
为什么添加完字段了，但是Actions里面没有可以运行的workflow呢？

**Comment by lyz7805** [comment]
> 为什么添加完字段了，但是Actions里面没有可以运行的workflow呢？

只要开启**Actions**就可以的。
具体问题请到 #16 回复。

**Comment by uloveme** [comment]
> 

大哥解决了吗？我也是添加了，但是workflow里空白

**Comment by lyz7805** [comment]
> > 
> 
> 大哥解决了吗？我也是添加了，但是workflow里空白

你提交一次试试看会触发构建不会？
