### ISSUE TITLE
action报错

### ISSUE THREAD

**Issue by ggyaya** [lyz7805/v2ray4flyio#18]
Error failed to fetch an image or build from source: error rendering push status stream: name unknown: app repository not found
这是为啥

**Comment by lyz7805** [comment]
> Error failed to fetch an image or build from source: error rendering push status stream: name unknown: app repository not found 这是为啥

`flyctl` 命令行工具更新之后，不能准确判断应用是否存在，所以造成没有创建应用，最后报这个错误。

我已经**修复**了这个问题，你可以重新试试。

**Comment by dinaau** [comment]
已经用你4月22号更新的deploy.sh代码
但是仍然报错
同楼主的error code
