### ISSUE TITLE
搭建在香港的节点被邮件警告即将收费

### ISSUE THREAD

**Issue by ChirmyRam** [lyz7805/v2ray4flyio#22]
搭建在香港的节点被邮件警告，说搭建代理应用是收费服务，24小时之内不删除应用的话将扣取费用。原文如下：

> [Fly.io] flhk requires a paid plan
> 
> Hello! You are receiving this email because you deployed an application (flhk.fly.dev) that is not allowed in our free tier. Our free tier is intended only for web applications. Proxy servers, TOR exit nodes, and BitTorrent apps are not allowed.
> 
> These kinds of applications are allowed on our paid plans. If you want to keep using this application on Fly.io, we will automatically upgrade you to our $10/month "Advanced" plan. If you would prefer not to upgrade, you have 24 hours to delete your application before you are charged. This is the command you need:
> 
> flyctl apps destroy flhk
> 
> Please let us know if you have any questions!
> 
>  -Kurt

同一账号下还有美国节点，尚为收到警告。索性我全部删掉了。

**Comment by lyz7805** [comment]
是的，我刚查了邮箱，也收到相同的邮件。

**Comment by suhipek** [comment]
我这边西雅图节点也被警告了，同账号下的东京还没被警告

**Comment by xianxin21** [comment]
洛杉矶节点也被警告，我是27日收到，但昨天才删除的应用，暂时未看到升级和扣费。

**Comment by xianxin21** [comment]
有人警告后被扣费了吗？

**Comment by lyz7805** [comment]
> 有人警告后被扣费了吗？

我在收到通知后就删除应用了，现在也没有继续用。

既然都广泛发了邮件通知，即使临时没有扣费，那未来说不定哪一天突然就给你扣了呢！
