### ISSUE TITLE
第三步报错

### ISSUE THREAD

**Issue by dinaau** [lyz7805/v2ray4flyio#23]
已经用了4月22号的deploy代码

仍然报错

==> Pushing image to fly
The push refers to repository [registry.fly.io/***]
708e5f72997d: Preparing
fcde3496feb4: Preparing
4fc242d5[82](https://github.com/xxxx/check_suite_focus=true#step:3:82)85: Preparing
Error failed to fetch an image or build from source: error rendering push status stream: name unknown: app repository not found

Error: Process completed with exit code 1.

**Comment by lyz7805** [comment]
现在不建议用 Fly 平台搭建 V2Ray ，官方开始封杀了
