### ISSUE TITLE
Error Could not resolve App

### ISSUE THREAD

**Issue by hiwyb** [lyz7805/v2ray4flyio#3]
<img width="878" alt="截屏2021-09-15 上午11 34 26" src="https://user-images.githubusercontent.com/69295750/133366368-b15db188-e485-4197-8b81-37a4b57927a8.png">
 
你好，遇到了这个问题

**Comment by lyz7805** [comment]
你是不是没有修改`fly.toml`中`app`名称？

**Comment by hiwyb** [comment]
> 你是不是没有修改`fly.toml`中`app`名称？

修改了哈，这是我的repo，可以帮忙看下

[hiwyb-v2ray4flyio](https://github.com/hiwyb/v2ray4flyio)

**Comment by lyz7805** [comment]
哈喽，之前的问题确实存在。
我这两天**重写了应用，现在改为自动部署，不需要修改代码，只要按照`README.md`中的加上`APP_NAME`配置，提交代码即可构建部署**
我已经测试过了没问题，你可以尝试一下
