### ISSUE TITLE
FLY_API_TOKEN、APP_NAME和UUID三个安全字段怎么填写

### ISSUE THREAD

**Issue by xuzhike123** [lyz7805/v2ray4flyio#4]
FLY_API_TOKEN、APP_NAME和UUID三个安全字段填写后显示无法运行

**Comment by lyz7805** [comment]
进入【Settings】，点击【Secrets】，按照要求增加这三个安全字段即可，可以看截图
![image](https://user-images.githubusercontent.com/19458454/143169767-1f1164d0-466a-478b-88af-6ea4fbcf1b82.png)

**Comment by lyz7805** [comment]
我刚看了你的[仓库](https://github.com/xuzhike123/v2ray4flyio/actions)，你似乎没有开启 **Actions** 功能

开启步骤看下图：
![image](https://user-images.githubusercontent.com/19458454/143170248-8e9d92b5-7270-46f7-879a-7876e4de7b06.png)

**Comment by xuzhike123** [comment]
谢谢，我是创建在另外一个子账号上的

lyz7805 ***@***.***> 于2021年11月24日周三 上午11:34写道：

**Comment by xuzhike123** [comment]
[image: image.png][image: image.png]
没办法部署，也没有生成Repository secrets,有没有详细点的教程，谢谢

許志舢 ***@***.***> 于2021年11月24日周三 下午1:14写道：

**Comment by lyz7805** [comment]
Issue #5 已经回复你了。
