### ISSUE TITLE
创建失败

### ISSUE THREAD

**Issue by xuzhike123** [lyz7805/v2ray4flyio#5]
![image](https://user-images.githubusercontent.com/46637868/143216351-9ad41791-5ed5-4d21-913a-659cbe1f1da6.png)

**Comment by lyz7805** [comment]
我刚看了[你仓库12月1号定时构建](https://github.com/xuzhike123/v2ray4flyio/runs/4376823090?check_suite_focus=true)记录，错误提示：**Please set APP_NAME first.**。
请你按照[README.md](https://github.com/lyz7805/v2ray4flyio/blob/main/README.md)中配置部署步骤设置，应该都可以成功。
