### ISSUE TITLE
Error failed to fetch an image or build from source: error rendering push status stream: name unknown: app repository not found

### ISSUE THREAD

**Issue by ccoz** [lyz7805/v2ray4flyio#7]

**Comment by lyz7805** [comment]
关联错误。。。

#9 实际修复 #8 问题

**Comment by fghwett** [comment]
使用最新的代码，还是出现这个问题

![image](https://user-images.githubusercontent.com/38271480/149862520-861d9602-689e-4b96-97a1-abcb71af2710.png)

**Comment by lyz7805** [comment]
等等，我正在解决。

**Comment by fghwett** [comment]
> 等等，我正在解决。

![image](https://user-images.githubusercontent.com/38271480/149904741-5e1fd666-7e27-4075-8078-a43aabc7f6e2.png)
最新版构建失败

**Comment by lyz7805** [comment]
我刚修改了`APP_NAME`，之后又重新执行了[Actions](https://github.com/lyz7805/v2ray4flyio/actions/runs/1711399152)，结果显示`Create app success.`。

--------------------
你首先看下3个**Secrets**是否都已创建。
1. APP_NAME
2. FLY_API_TOKEN
3. UUID

**Comment by fghwett** [comment]
> 我刚修改了`APP_NAME`，之后又重新执行了[Actions](https://github.com/lyz7805/v2ray4flyio/actions/runs/1711399152)，结果显示`Create app success.`。
> 
> 你首先看下3个**Secrets**是否都已创建。
> 
> 1. APP_NAME
> 2. FLY_API_TOKEN
> 3. UUID

我重新fork了项目，尝试了两次结果还是一样
![image](https://user-images.githubusercontent.com/38271480/150098166-414f83a3-aa02-4e76-a080-b082d9c4111a.png)

**Comment by lyz7805** [comment]
@fghwett 
把 `deploy.sh` 第19行改为 `flyctl apps create "${APP_NAME}"` 再提交，看创建时候控制台显示什么结果。
https://github.com/lyz7805/v2ray4flyio/commit/62ea2eb2104ed77ef34f936ee96c9ab1caac910d#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0

**Comment by fghwett** [comment]
> @fghwett 把 `deploy.sh` 第19行改为 `flyctl apps create "${APP_NAME}"` 再提交，看创建时候控制台显示什么结果。 [62ea2eb#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0](https://github.com/lyz7805/v2ray4flyio/commit/62ea2eb2104ed77ef34f936ee96c9ab1caac910d#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0)

Error We need your payment information to continue!
哭了，注册的时候用的GitHub没有提示绑卡，现在报错了。。。

**Comment by lyz7805** [comment]
嗯，我看到了，绑卡好像没有限制，可以用银联信用卡，你按照系统提示绑卡应该就没有问题啦

**Comment by fghwett** [comment]
> 嗯，我看到了，绑卡好像没有限制，可以用银联信用卡，你按照系统提示绑卡应该就没有问题啦

放弃放弃，被官方标记高风险用户了，头大
